In [1]:
from chop.models import get_model

model = get_model("chronos-2", pretrained=True)

/home/lucas/mase/.venv/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/lucas/mase/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/lucas/mase/.venv/lib/python3.11/site-packages/timm/models/helpers.py:7: FutureWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)


In [ ]:
from chop import MaseGraph
import torch
import chop.passes as passes

batch_size = 1

print(model.config.chronos_config)
c_len = model.config.chronos_config["context_length"]

my_dummy_inputs = {
    "context": torch.randn((batch_size, c_len)),
    "context_mask": torch.ones((batch_size, c_len), dtype=torch.bool),
    "group_ids": torch.zeros((batch_size,), dtype=torch.long)
}

mg = MaseGraph(
    model,
    hf_input_names=[
        "context", 
        "context_mask", 
        "group_ids"
    ],
)


mg, _ = passes.init_metadata_analysis_pass(mg)
mg, _ = passes.add_common_metadata_analysis_pass(mg, pass_args={"dummy_in": my_dummy_inputs})

`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.


{'context_length': 8192, 'input_patch_size': 16, 'input_patch_stride': 16, 'max_output_patches': 64, 'output_patch_size': 16, 'quantiles': [0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 0.99], 'time_encoding_scale': 8192, 'use_arcsinh': True, 'use_reg_token': True}
tensor([[ 0.0770, -0.7389, -1.3498,  ..., -0.1503,  0.1318, -0.7125]])
tensor([[ 0.0770, -0.7389, -1.3498,  ..., -0.1503,  0.1318, -0.7125]])
tensor([[True, True, True,  ..., True, True, True]])
tensor([[ 0.0770, -0.7389, -1.3498,  ..., -0.1503,  0.1318, -0.7125]])
tensor([[ 0.0770, -0.7389, -1.3498,  ..., -0.1503,  0.1318, -0.7125]])
tensor([[ 0.0766, -0.7394, -1.3502,  ..., -0.1508,  0.1313, -0.7130]])
tensor([[0.0059, 0.5467, 1.8232,  ..., 0.0227, 0.0172, 0.5083]])
tensor([[0.9758]])
tensor([[ 0.0774, -0.6920, -1.1186,  ..., -0.1521,  0.1326, -0.6704]])
tensor([[ 0.0774, -0.6920, -1.1186,  ..., -0.1521,  0.1326, -0.6704]])
tensor([[1., 1., 1.,  ..., 1., 1., 